services:
  postgres:
    image: postgres:15
    container_name: analyzer_postgres
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome
    ports:
      - "6432:5432"
